version: '3'

services:

  node:
    image: node
    ports:
      - 3000:3000
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    entrypoint:
      - bash
      - -c
      - "npm install && node app.js"
